# Auto-generated by tools/sync_config_docstrings.py — do not edit by hand.

from __future__ import annotations

from .serializable_config import SerializableConfig
from pathlib import Path
from typing import Any, ClassVar

class ConfigContainer(SerializableConfig):
    """Manage an ordered collection of configuration references.

    Construction resolves entries using ``SerializableConfig.from_any()``.
    Existing objects are retained by identity; payloads, serialized strings,
    and file references are loaded into objects. Relative file references use
    the containing config file or the active path-resolution context.
    Without either anchor, paths resolve against the construction-time working
    directory. Passing the container to a Simulation does not re-resolve them;
    use ``resolving_paths_relative_to()`` around construction to choose a base.

    Serialization embeds the resolved configurations inline, not as external
    references. Order and repeated entries are retained, but shared identity
    does not survive saving and reloading. Nested containers are supported
    without flattening; directory scanning and execution are not performed.

    Args:
        configs: (list[SerializableConfig | str | Path | dict[str, Any]])
            |OPTIONAL| Config objects, tagged payloads, YAML/JSON strings, or
            individual config file references. Defaults to a new empty list.
            After construction, add only live configuration objects to this list."""
    CONFIG_TYPE: ClassVar[str]
    SUBCLASS: ClassVar[str]
    configs: list[SerializableConfig | str | Path | dict[str, Any]]
    def __init__(
        self,
        *,
        configs: list[SerializableConfig | str | Path | dict[str, Any]] = ...,
    ) -> None:
        """Manage an ordered collection of configuration references.

        Construction resolves entries using ``SerializableConfig.from_any()``.
        Existing objects are retained by identity; payloads, serialized strings,
        and file references are loaded into objects. Relative file references use
        the containing config file or the active path-resolution context.
        Without either anchor, paths resolve against the construction-time working
        directory. Passing the container to a Simulation does not re-resolve them;
        use ``resolving_paths_relative_to()`` around construction to choose a base.

        Serialization embeds the resolved configurations inline, not as external
        references. Order and repeated entries are retained, but shared identity
        does not survive saving and reloading. Nested containers are supported
        without flattening; directory scanning and execution are not performed.

        Args:
            configs: (list[SerializableConfig | str | Path | dict[str, Any]])
                |OPTIONAL| Config objects, tagged payloads, YAML/JSON strings, or
                individual config file references. Defaults to a new empty list.
                After construction, add only live configuration objects to this list."""
