# Auto-generated by tools/sync_config_docstrings.py — do not edit by hand.

from __future__ import annotations

from .datapoint import _Datapoint

from abc import abstractmethod
from typing import Any, ClassVar

class _Diagnostic(_Datapoint):
    """Abstract datapoint populated by explicit or scheduled analysis.

    Concrete subclasses declare a ``SUBCLASS`` tag and implement ``_analyze``
    to return a dictionary of results. Analysis never runs during construction,
    loading, or serialization. Call ``analyze()`` to replace ``data`` and mark
    this instance complete. Serializing an incomplete instance logs a warning
    but still saves its current data.

    Completion is runtime-only: loading saved results preserves ``data`` but
    starts a new, incomplete instance. Subclasses should declare their analysis
    inputs as normal init fields so those inputs can also be saved and reloaded.

    Subclasses set ``RUN_BEFORE_SIMULATION`` to select automatic analysis at
    the end of simulation setup (True) or after simulation stepping (False,
    the default). This class-level policy is not an instance input or serialized
    parameter.

    Args:
        data: (dict[str, Any]) |OPTIONAL| Stored values. Defaults to a new empty
            dictionary. Values use the standard configuration serialization
            conversions; arbitrary dictionaries are not interpreted as configs."""
    RUN_BEFORE_SIMULATION: ClassVar[bool]
    def __init__(
        self,
        *,
        data: dict[str, Any] = ...,
    ) -> None:
        """Abstract datapoint populated by explicit or scheduled analysis.

        Concrete subclasses declare a ``SUBCLASS`` tag and implement ``_analyze``
        to return a dictionary of results. Analysis never runs during construction,
        loading, or serialization. Call ``analyze()`` to replace ``data`` and mark
        this instance complete. Serializing an incomplete instance logs a warning
        but still saves its current data.

        Completion is runtime-only: loading saved results preserves ``data`` but
        starts a new, incomplete instance. Subclasses should declare their analysis
        inputs as normal init fields so those inputs can also be saved and reloaded.

        Subclasses set ``RUN_BEFORE_SIMULATION`` to select automatic analysis at
        the end of simulation setup (True) or after simulation stepping (False,
        the default). This class-level policy is not an instance input or serialized
        parameter.

        Args:
            data: (dict[str, Any]) |OPTIONAL| Stored values. Defaults to a new empty
                dictionary. Values use the standard configuration serialization
                conversions; arbitrary dictionaries are not interpreted as configs."""
    @property
    def analysis_complete(self) -> bool:
        """Whether the most recent explicit analysis completed successfully."""
        ...
    @abstractmethod
    def _analyze(self) -> dict[str, Any]:
        """Perform analysis and return the desired result dictionary."""
        ...
    def analyze(self) -> None:
        """Run analysis and store its results, marking completion only on success.

        Every call reruns ``_analyze()``. If it raises or returns something other
        than a dictionary, completion remains false and this wrapper does not
        replace the previous data. Mutations or external side effects performed
        by subclass code are not rolled back.

        Raises:
            TypeError: If ``_analyze()`` does not return a dictionary."""
        ...
    def to_dict(self, *, include_nones: bool=True) -> dict[str, Any]:
        """Serialize current inputs and results, warning if analysis is incomplete."""
        ...
